// Parameterized synchronous FIFO
// Generated by OpenHands foundry workflow for KAN-87

module sync_fifo #(
  parameter int WIDTH = 8,
  parameter int DEPTH = 16
) (
  input  logic             clk,
  input  logic             rst_n,
  input  logic             wr_en,
  input  logic             rd_en,
  input  logic [WIDTH-1:0] din,
  output logic [WIDTH-1:0] dout,
  output logic             full,
  output logic             empty
);

  localparam int ADDR_WIDTH = $clog2(DEPTH);
  localparam int ADDR_MAX = DEPTH - 1;
  /* verilator lint_off WIDTHTRUNC */
  localparam logic [ADDR_WIDTH:0] DEPTH_VAL = DEPTH;
  /* verilator lint_on WIDTHTRUNC */

  logic [WIDTH-1:0] mem [0:DEPTH-1];
  logic [ADDR_WIDTH-1:0] wr_ptr;
  logic [ADDR_WIDTH-1:0] rd_ptr;
  logic [ADDR_WIDTH:0] count;

  assign full = (count >= DEPTH_VAL);
  assign empty = (count == '0);

  always_ff @(posedge clk) begin
    if (!rst_n) begin
      wr_ptr <= '0;
      rd_ptr <= '0;
      count <= '0;
      dout <= '0;
    end else begin
      // Write operation
      if (wr_en && !full) begin
        mem[wr_ptr] <= din;
        if (wr_ptr == ADDR_MAX[ADDR_WIDTH-1:0])
          wr_ptr <= '0;
        else
          wr_ptr <= wr_ptr + 1'b1;
      end

      // Read operation: capture data before advancing pointer
      if (rd_en && !empty) begin
        dout <= mem[rd_ptr];
        if (rd_ptr == ADDR_MAX[ADDR_WIDTH-1:0])
          rd_ptr <= '0;
        else
          rd_ptr <= rd_ptr + 1'b1;
      end

      // Update count
      case ({wr_en && !full, rd_en && !empty})
        2'b10: count <= count + 1'b1;
        2'b01: count <= count - 1'b1;
        default: count <= count;
      endcase
    end
  end

endmodule
